version: '3.1'

services:

  db:
    image: 'library/postgres:12.6-alpine'
    restart: always
    environment:
      - POSTGRES_PASSWORD=super
    ports:
      - 5432:5432
    networks:
      - private_network
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

volumes:
  postgres_data:

networks:
  private_network: